version: '3.8'

services:
  web:
    build: .
    container_name: godeye-web
    env_file:
      - ../../.env
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: godeye-db
    env_file:
      - ../../.env
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"